
spring:
  application:
    name: department-service

#  cloud:
#    config:
#      enabled: false
  config:
    import: "optional:configserver:http://localhost:8002"

  datasource:
    url: jdbc:mysql://localhost:3306/department_service
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /v1/docs/department-service
  swagger-ui:
    path: /swagger-ui.html
