spring:
  application:
    name: employee-service

  config:
    import: "optional:configserver:http://localhost:8002"

  datasource:
    url: jdbc:mysql://localhost:3306/employee_service
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

#springdoc:
#  api-docs:
#    enabled: true
#    path: /v1/docs/employee-service
#  swagger-ui:
#    path: /swagger-ui.html